version: '3.4'

services:
  dev:
    image: protein-mass-calc-dev
    build: docker/dev
    volumes:
      - $PWD:/opt/protein-mass-calculator
    ports:
     - 8080:8080
  redis:
    image: redis
  loki:
    image: grafana/loki
  influx:
    image: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=proteinmass  
      - DOCKER_INFLUXDB_INIT_ORG=pmc
      - DOCKER_INFLUXDB_INIT_BUCKET=pmc-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=PMCADMINTOKEN
    ports:
     - 8086:8086
  grafana:
    image: pmc-grafana
    build: docker/grafana
    environment:
      - INFLUX_TOKEN=PMCADMINTOKEN
    ports:
      - 3000:3000
    secrets:
      - admin_password

secrets:
  admin_password:
    file: ./admin_pw