apiVersion: 1

datasources:
- name: Infux
  type: influxdb
  access: proxy
  url: http://influx:8086
  secureJsonData:
    token: $INFLUX_TOKEN
  jsonData:
    version: Flux
    organization: pmc
    defaultBucket: pmc-metrics
    tlsSkipVerify: true