#!/bin/bash
set -e
CMD_ARGS=("$@")
DOCKER_SWITCHES=${DOCKER_SWITCHES:-''}
DEV_SVC='dev'
DEV_WORK_DIR=${DEV_WORK_DIR:-/opt/protein-mass-calculator}

# Get root directory for entire project
PROJECT_ROOT="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

# Run passed command inside dev docker-compose service.
docker-compose exec -w ${DEV_WORK_DIR} ${DEV_SVC} ${CMD_ARGS[@]}
