{
 "title": "Protein Mass Calculator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pmc-metrics\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"CACHE_HITS\"  \r\n)"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pmc-metrics\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"CACHE_MISSES\"  \r\n)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pmc-metrics\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"ERROR_COUNT\"  \r\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"protein-mass-calculator\"}"
    }
   ]
  }
 ]
}